name: Daily Sync & Modify

on:
  schedule:
    - cron: '0 1 * * *'  # 每天北京时间9点（UTC 1点）
  workflow_dispatch:

jobs:
  sync-and-modify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout my-edits branch
      uses: actions/checkout@v3
      with:
        ref: my-edits
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Fetch latest config file from upstream
      run: |
        git remote add upstream https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever.git
        git fetch upstream
        git checkout upstream/release -- sr_top500_whitelist_ad.conf

    - name: Insert Proxy Group & Rules around [Rule]
      run: |
         # 删除 Proxy Group 区块（BEGIN 到 END）
         sed -i '/# BEGIN-PR-GROUP-CUSTOM/,/# END-PR-GROUP-CUSTOM/d' sr_top500_whitelist_ad.conf

         # 插入 pr_group.txt 到 [Rule] 上方
         awk '/^\[Rule\]/ { system("cat pr_group.txt"); print; next } 1' sr_top500_whitelist_ad.conf > tmp && mv tmp sr_top500_whitelist_ad.conf

         # 删除 Rule 区块（BEGIN 到 END）
         sed -i '/# BEGIN-RULE-CUSTOM/,/# END-RULE-CUSTOM/d' sr_top500_whitelist_ad.conf

         # 插入 rule.txt 到 [Rule] 下方
         awk 'BEGIN { found=0 }
           /^\[Rule\]/ { print; found=1; next }
           found==1 && !inserted {
           system("cat rule.txt");
           inserted=1
          }
          { print }' sr_top500_whitelist_ad.conf > tmp && mv tmp sr_top500_whitelist_ad.conf

        




    - name: Commit and Push
      run: |
        git add sr_top500_whitelist_ad.conf
        git commit -m "Auto update on $(date '+%Y-%m-%d')" || echo "No changes"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} my-edits
